### ISSUE TITLE
Please consider appending "minimum_chrome_version" to manifest.json

### ISSUE THREAD

**Issue by ThinkLoudly** [pd4d10/tampery#1]
Unfortunately async function [only works in Chrome 55 and above](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Browser_compatibility) :(

Cool ext. An example script that allows CORS would be handy.

**Comment by pd4d10** [comment]
@ThinkLoudly Seems it only works at Chrome 63+ because it uses dynamic import.

minimum_chrome_version set to "63" and CORS examples added at v0.0.3.

Thanks for you suggestion
